[package]
name = "geckopandacli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
geckopanda = "0.2.0"

[[bin]]
name = "geckopanda"
path = "src/main.rs"

